services:
  - type: web
    name: mystery-box-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: ADMIN_PHONE
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: mystery-box-db
          property: connectionString

databases:
  - name: mystery-box-db
    databaseName: bot_discount
    user: bot_user 